config/routes.rb
Release::Application.routes.draw do
  resources :map_images

  resources :map_types

  resources :cal_event_cats

  resources :pois

  resources :poi_cats

  resources :jsonfiles

  resources :venues

  resources :installations

  resources :venue_imports, :only => [:index]
  resources :venue_import_releases, :only => [:index, :new, :pubto]
  resources :importjsons, :only => [:index, :venue, :poi_cat]

  match '/imports',              :to => 'venue_imports#index'
  match '/imports/:vendir',          :to => 'venue_import_releases#index'
  match '/imports/:vendir/new',  :to => 'venue_import_releases#new'
  match '/imports/:vendir/rev/:revndx/pubto',  :to => 'venue_import_releases#pubto'
  match '/imports/:vendir/rev/:revndx',  :to => 'importjsons#index'
  match '/imports/:vendir/rev/:revndx/venue',  :to => 'importjsons#venue'
  match '/imports/:vendir/rev/:revndx/poi_cat',  :to => 'importjsons#poi_cat'
  match '/page/:filename.:format', :to => 'static_pages#page'

end

app/models/installation.rb
# == Schema Information
# Schema version: 20110208104327
#
# Table name: installations
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  description  :text
#  venue_id     :integer
#  release      :integer
#  migration_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Installation < ActiveRecord::Base
  belongs_to :venue
  belongs_to :migration
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  # GET /installations
  # GET /installations.xml
  def index
    @installations = Installation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @installations }
    end
  end

  # GET /installations/1
  # GET /installations/1.xml
  def show
    @installation = Installation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @installation }
    end
  end

  # GET /installations/new
  # GET /installations/new.xml
  def new
    @installation = Installation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @installation }
    end
  end

  # GET /installations/1/edit
  def edit
    @installation = Installation.find(params[:id])
  end

  # POST /installations
  # POST /installations.xml
  def create
    @installation = Installation.new(params[:installation])

    respond_to do |format|
      if @installation.save
        format.html { redirect_to(@installation, :notice => 'Installation was successfully created.') }
        format.xml  { render :xml => @installation, :status => :created, :location => @installation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @installation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /installations/1
  # PUT /installations/1.xml
  def update
    @installation = Installation.find(params[:id])

    respond_to do |format|
      if @installation.update_attributes(params[:installation])
        format.html { redirect_to(@installation, :notice => 'Installation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @installation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /installations/1
  # DELETE /installations/1.xml
  def destroy
    @installation = Installation.find(params[:id])
    @installation.destroy

    respond_to do |format|
      format.html { redirect_to(installations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/views/installations/_form.html.erb
<%= form_for(@installation) do |f| %>
  <% if @installation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@installation.errors.count, "error") %> prohibited this installation from being saved:</h2>

      <ul>
      <% @installation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="field">
    <%= f.label :migration %><br />
    <%= f.text_field :migration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/installations/edit.html.erb
<h1>Editing installation</h1>

<%= render 'form' %>

<%= link_to 'Show', @installation %> |
<%= link_to 'Back', installations_path %>

app/views/installations/index.html.erb
<h1>Listing installations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Venue</th>
    <th>Release</th>
    <th>Migration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @installations.each do |installation| %>
  <tr>
    <td><%= installation.name %></td>
    <td><%= installation.description %></td>
    <td><%= installation.venue %></td>
    <td><%= installation.release %></td>
    <td><%= installation.migration %></td>
    <td><%= link_to 'Show', installation %></td>
    <td><%= link_to 'Edit', edit_installation_path(installation) %></td>
    <td><%= link_to 'Destroy', installation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Installation', new_installation_path %>

app/views/installations/new.html.erb
<h1>New installation</h1>

<%= render 'form' %>

<%= link_to 'Back', installations_path %>

app/views/installations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @installation.name %>
</p>

<p>
  <b>Description:</b>
  <%= @installation.description %>
</p>

<p>
  <b>Venue:</b>
  <%= @installation.venue %>
</p>

<p>
  <b>Release:</b>
  <%= @installation.release %>
</p>

<p>
  <b>Migration:</b>
  <%= @installation.migration %>
</p>


<%= link_to 'Edit', edit_installation_path(@installation) %> |
<%= link_to 'Back', installations_path %>