config/routes.rb
Release::Application.routes.draw do
  resources :map_images

  resources :map_types

  resources :cal_event_cats

  resources :pois

  resources :poi_cats

  resources :jsonfiles

  resources :venues

  resources :installations

  resources :venue_imports, :only => [:index]
  resources :venue_import_releases, :only => [:index, :new, :pubto]
  resources :importjsons, :only => [:index, :venue, :poi_cat]

  match '/imports',              :to => 'venue_imports#index'
  match '/imports/:vendir',          :to => 'venue_import_releases#index'
  match '/imports/:vendir/new',  :to => 'venue_import_releases#new'
  match '/imports/:vendir/rev/:revndx/pubto',  :to => 'venue_import_releases#pubto'
  match '/imports/:vendir/rev/:revndx',  :to => 'importjsons#index'
  match '/imports/:vendir/rev/:revndx/venue',  :to => 'importjsons#venue'
  match '/imports/:vendir/rev/:revndx/poi_cat',  :to => 'importjsons#poi_cat'
  match '/page/:filename.:format', :to => 'static_pages#page'

end

app/models/poi_cat.rb
# == Schema Information
# Schema version: 20110209122758
#
# Table name: poi_cats
#
#  id          :integer         not null, primary key
#  uid         :integer
#  mapuid      :integer
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class PoiCat < ActiveRecord::Base
	# TODO: put in validations for no spaces in venue name
	# TODO: This was updated from Venue. the non-uniques should be extracted and 
	#	handled through modules
	
	def self.to_json 
		ven_arr = PoiCat.all
		str_json = "[\n"
		str_add_comma = ""
		ven_arr.each do | ven_one |
			str_json << str_add_comma
			str_json << "\t{\"point_of_interest_category\":\n"
			str_json << "\t\t{\n"

			# integer
			str_json << "\t\t\"uid\": "
			str_json << ven_one.uid.to_s
			str_json << ",\n"
			
			# integer
			str_json << "\t\t\"mapUid\": "
			str_json << ven_one.mapuid.to_s
			str_json << ",\n"
			
			# string
			str_json << "\t\t\"name\": \""
			str_json << ven_one.name
			str_json << "\",\n"

            # string and last item (no ',' in last line)
			str_json << "\t\t\"description\": \""
			str_json << ven_one.description
			str_json << "\"\n"
			
			str_json << "\t\t}\n"
			str_json << "\t}"
		    str_add_comma = ",\n"
		end
		str_json << "\n]\n"
		
		return str_json
	end
	
	# regular expessions can be tested at quickly at rubular.com
	# this can be used in all modules by just changing the variables described
	def self.create_match_array_from_json ( json_string )
		# Unique to Venue 
		rgxMatch = /\{\s*"point_of_interest_category":\s*\{\s*"uid":\s*(\d*),\s*"mapUid":\s*(\d*),\s*"name":\s*"(.*)",\s*"description":\s*"(.*)"\s*\}\s*\}/
		
		# this is generick
		rgxMatch.match(json_string) # returns the matched data points in an array
	end
	
	def self.flds_to_match
		# Unique to Venue 
		return 4
	end
	
	def self.match_obj_count ( match_arr )
		if match_arr.size > self.flds_to_match
			return (match_arr.size-1)/self.flds_to_match
		else
			return 0
		end
	end
	
	def self.new_from_match_array ( match_arr, obj_ndx )
		# Unique to venue all of this functino
		obj_this = PoiCat.new
		fld_ndx = (obj_ndx * self.flds_to_match) + 1
		obj_this.uid = match_arr[fld_ndx].to_i
		obj_this.mapuid = match_arr[fld_ndx+1].to_i
		obj_this.name = match_arr[fld_ndx+2]
		obj_this.description = match_arr[fld_ndx+3]
		return obj_this
	end
	
	def self.new_from_hash_array ( hash_arr, obj_cur )
		hash_one = hash_arr[ obj_cur ]
		obj_this = PoiCat.new
        obj_this.uid = hash_one["point_of_interest_category"]["uid"]
        obj_this.mapuid = hash_one["point_of_interest_category"]["mapUid"]
        obj_this.name = hash_one["point_of_interest_category"]["name"]
        obj_this.description = hash_one["point_of_interest_category"]["description"]
		return obj_this
	end
	
	def self.build_arr_from_json( str_json ) 
		hash_arr = JSON.parse( str_json )
		obj_arr = [] 
		obj_count = hash_arr.size
		
		obj_cur = 0
		
		while obj_cur < obj_count do
			obj_arr << self.new_from_hash_array ( hash_arr, obj_cur )
			obj_cur = obj_cur + 1 
		end
		
		return obj_arr
	end
	
	def self.was_build_arr_from_json( str_json ) 
		match_arr = self.create_match_array_from_json ( str_json )
		obj_arr = [] 
		obj_count = self.match_obj_count match_arr
		obj_cur = 0
		
		while obj_cur < obj_count do
			obj_arr << self.new_from_match_array ( match_arr, obj_cur )
			obj_cur = obj_cur + 1 
		end
		
		return obj_arr
	end

	def self.obj_identical?( old_obj, new_obj )
		# Unique to Venue 
		return (old_obj.uid == new_obj.uid) && (old_obj.mapuid == new_obj.mapuid) && (old_obj.name == new_obj.name) && (old_obj.description == new_obj.description)
	end
	
	def self.array_identical?( old_arr, new_arr )
		arr_match = false
		new_arr.each do | new_obj |
			arr_match = false
			old_arr.each do | old_obj |
				if self.obj_identical?( new_obj, old_obj )
					arr_match = true
					break
				end
			end
			if arr_match == false
				return false
			end 
		end
		# test is run in each direction, to insure full coverage
		# makes it slightly slower, but these are small arrays, and rare operations
		arr_match = false
		old_arr.each do | old_obj |
			arr_match = false
			new_arr.each do | new_obj |
				if self.obj_identical?( new_obj, old_obj )
					arr_match = true
					break
				end
			end
			if arr_match == false
				return false
			end 
		end
		return arr_match
	end
	
end

app/controllers/poi_cats_controller.rb
class PoiCatsController < ApplicationController
  # GET /poi_cats
  # GET /poi_cats.xml
  def index
    @poi_cats = PoiCat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @poi_cats }
    end
  end

  # GET /poi_cats/1
  # GET /poi_cats/1.xml
  def show
    @poi_cat = PoiCat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @poi_cat }
    end
  end

  # GET /poi_cats/new
  # GET /poi_cats/new.xml
  def new
    @poi_cat = PoiCat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @poi_cat }
    end
  end

  # GET /poi_cats/1/edit
  def edit
    @poi_cat = PoiCat.find(params[:id])
  end

  # POST /poi_cats
  # POST /poi_cats.xml
  def create
    @poi_cat = PoiCat.new(params[:poi_cat])

    respond_to do |format|
      if @poi_cat.save
        format.html { redirect_to(@poi_cat, :notice => 'Poi cat was successfully created.') }
        format.xml  { render :xml => @poi_cat, :status => :created, :location => @poi_cat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @poi_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /poi_cats/1
  # PUT /poi_cats/1.xml
  def update
    @poi_cat = PoiCat.find(params[:id])

    respond_to do |format|
      if @poi_cat.update_attributes(params[:poi_cat])
        format.html { redirect_to(@poi_cat, :notice => 'Poi cat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @poi_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /poi_cats/1
  # DELETE /poi_cats/1.xml
  def destroy
    @poi_cat = PoiCat.find(params[:id])
    @poi_cat.destroy

    respond_to do |format|
      format.html { redirect_to(poi_cats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/poi_cats_helper.rb
module PoiCatsHelper
end

app/views/poi_cats/_form.html.erb
<%= form_for(@poi_cat) do |f| %>
  <% if @poi_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poi_cat.errors.count, "error") %> prohibited this poi_cat from being saved:</h2>

      <ul>
      <% @poi_cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :mapuid %><br />
    <%= f.text_field :mapuid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poi_cats/edit.html.erb
<h1>Editing poi_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @poi_cat %> |
<%= link_to 'Back', poi_cats_path %>

app/views/poi_cats/index.html.erb
<h1>Listing poi_cats</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Mapuid</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @poi_cats.each do |poi_cat| %>
  <tr>
    <td><%= poi_cat.uid %></td>
    <td><%= poi_cat.mapuid %></td>
    <td><%= poi_cat.name %></td>
    <td><%= poi_cat.description %></td>
    <td><%= link_to 'Show', poi_cat %></td>
    <td><%= link_to 'Edit', edit_poi_cat_path(poi_cat) %></td>
    <td><%= link_to 'Destroy', poi_cat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poi cat', new_poi_cat_path %>

app/views/poi_cats/new.html.erb
<h1>New poi_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', poi_cats_path %>

app/views/poi_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @poi_cat.uid %>
</p>

<p>
  <b>Mapuid:</b>
  <%= @poi_cat.mapuid %>
</p>

<p>
  <b>Name:</b>
  <%= @poi_cat.name %>
</p>

<p>
  <b>Description:</b>
  <%= @poi_cat.description %>
</p>


<%= link_to 'Edit', edit_poi_cat_path(@poi_cat) %> |
<%= link_to 'Back', poi_cats_path %>