config/routes.rb
Release::Application.routes.draw do
  resources :map_images

  resources :map_types

  resources :cal_event_cats

  resources :pois

  resources :poi_cats

  resources :jsonfiles

  resources :venues

  resources :installations

  resources :venue_imports, :only => [:index]
  resources :venue_import_releases, :only => [:index, :new, :pubto]
  resources :importjsons, :only => [:index, :venue, :poi_cat]

  match '/imports',              :to => 'venue_imports#index'
  match '/imports/:vendir',          :to => 'venue_import_releases#index'
  match '/imports/:vendir/new',  :to => 'venue_import_releases#new'
  match '/imports/:vendir/rev/:revndx/pubto',  :to => 'venue_import_releases#pubto'
  match '/imports/:vendir/rev/:revndx',  :to => 'importjsons#index'
  match '/imports/:vendir/rev/:revndx/venue',  :to => 'importjsons#venue'
  match '/imports/:vendir/rev/:revndx/poi_cat',  :to => 'importjsons#poi_cat'
  match '/page/:filename.:format', :to => 'static_pages#page'

end

app/models/jsonfile.rb
# == Schema Information
# Schema version: 20110209122758
#
# Table name: jsonfiles
#
#  id          :integer         not null, primary key
#  filename    :string(255)
#  description :text
#  jsonparse   :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Jsonfile < ActiveRecord::Base
end

app/controllers/jsonfiles_controller.rb
class JsonfilesController < ApplicationController
  # GET /jsonfiles
  # GET /jsonfiles.xml
  def index
    @jsonfiles = Jsonfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jsonfiles }
    end
  end

  # GET /jsonfiles/1
  # GET /jsonfiles/1.xml
  def show
    @jsonfile = Jsonfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @jsonfile }
    end
  end

  # GET /jsonfiles/new
  # GET /jsonfiles/new.xml
  def new
    @jsonfile = Jsonfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @jsonfile }
    end
  end

  # GET /jsonfiles/1/edit
  def edit
    @jsonfile = Jsonfile.find(params[:id])
  end

  # POST /jsonfiles
  # POST /jsonfiles.xml
  def create
    @jsonfile = Jsonfile.new(params[:jsonfile])

    respond_to do |format|
      if @jsonfile.save
        format.html { redirect_to(@jsonfile, :notice => 'Jsonfile was successfully created.') }
        format.xml  { render :xml => @jsonfile, :status => :created, :location => @jsonfile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @jsonfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jsonfiles/1
  # PUT /jsonfiles/1.xml
  def update
    @jsonfile = Jsonfile.find(params[:id])

    respond_to do |format|
      if @jsonfile.update_attributes(params[:jsonfile])
        format.html { redirect_to(@jsonfile, :notice => 'Jsonfile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @jsonfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jsonfiles/1
  # DELETE /jsonfiles/1.xml
  def destroy
    @jsonfile = Jsonfile.find(params[:id])
    @jsonfile.destroy

    respond_to do |format|
      format.html { redirect_to(jsonfiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/jsonfiles_helper.rb
module JsonfilesHelper
end

app/views/jsonfiles/_form.html.erb
<%= form_for(@jsonfile) do |f| %>
  <% if @jsonfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jsonfile.errors.count, "error") %> prohibited this jsonfile from being saved:</h2>

      <ul>
      <% @jsonfile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :jsonparse %><br />
    <%= f.text_area :jsonparse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jsonfiles/edit.html.erb
<h1>Editing jsonfile</h1>

<%= render 'form' %>

<%= link_to 'Show', @jsonfile %> |
<%= link_to 'Back', jsonfiles_path %>

app/views/jsonfiles/index.html.erb
<h1>Listing jsonfiles</h1>

<table>
  <tr>
    <th>Filename</th>
    <th>Description</th>
    <th>Jsonparse</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jsonfiles.each do |jsonfile| %>
  <tr>
    <td><%= jsonfile.filename %></td>
    <td><%= jsonfile.description %></td>
    <td><%= jsonfile.jsonparse %></td>
    <td><%= link_to 'Show', jsonfile %></td>
    <td><%= link_to 'Edit', edit_jsonfile_path(jsonfile) %></td>
    <td><%= link_to 'Destroy', jsonfile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jsonfile', new_jsonfile_path %>

app/views/jsonfiles/new.html.erb
<h1>New jsonfile</h1>

<%= render 'form' %>

<%= link_to 'Back', jsonfiles_path %>

app/views/jsonfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Filename:</b>
  <%= @jsonfile.filename %>
</p>

<p>
  <b>Description:</b>
  <%= @jsonfile.description %>
</p>

<p>
  <b>Jsonparse:</b>
  <%= @jsonfile.jsonparse %>
</p>


<%= link_to 'Edit', edit_jsonfile_path(@jsonfile) %> |
<%= link_to 'Back', jsonfiles_path %>