config/routes.rb
Release::Application.routes.draw do
  resources :map_images

  resources :map_types

  resources :cal_event_cats

  resources :pois

  resources :poi_cats

  resources :jsonfiles

  resources :venues

  resources :installations

  resources :venue_imports, :only => [:index]
  resources :venue_import_releases, :only => [:index, :new, :pubto]
  resources :importjsons, :only => [:index, :venue, :poi_cat]

  match '/imports',              :to => 'venue_imports#index'
  match '/imports/:vendir',          :to => 'venue_import_releases#index'
  match '/imports/:vendir/new',  :to => 'venue_import_releases#new'
  match '/imports/:vendir/rev/:revndx/pubto',  :to => 'venue_import_releases#pubto'
  match '/imports/:vendir/rev/:revndx',  :to => 'importjsons#index'
  match '/imports/:vendir/rev/:revndx/venue',  :to => 'importjsons#venue'
  match '/imports/:vendir/rev/:revndx/poi_cat',  :to => 'importjsons#poi_cat'
  match '/page/:filename.:format', :to => 'static_pages#page'

end

app/models/cal_event_cat.rb
# == Schema Information
# Schema version: 20110209175452
#
# Table name: cal_event_cats
#
#  id          :integer         not null, primary key
#  uid         :integer
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class CalEventCat < ActiveRecord::Base
end

app/controllers/cal_event_cats_controller.rb
class CalEventCatsController < ApplicationController
  # GET /cal_event_cats
  # GET /cal_event_cats.xml
  def index
    @cal_event_cats = CalEventCat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cal_event_cats }
    end
  end

  # GET /cal_event_cats/1
  # GET /cal_event_cats/1.xml
  def show
    @cal_event_cat = CalEventCat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cal_event_cat }
    end
  end

  # GET /cal_event_cats/new
  # GET /cal_event_cats/new.xml
  def new
    @cal_event_cat = CalEventCat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cal_event_cat }
    end
  end

  # GET /cal_event_cats/1/edit
  def edit
    @cal_event_cat = CalEventCat.find(params[:id])
  end

  # POST /cal_event_cats
  # POST /cal_event_cats.xml
  def create
    @cal_event_cat = CalEventCat.new(params[:cal_event_cat])

    respond_to do |format|
      if @cal_event_cat.save
        format.html { redirect_to(@cal_event_cat, :notice => 'Cal event cat was successfully created.') }
        format.xml  { render :xml => @cal_event_cat, :status => :created, :location => @cal_event_cat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cal_event_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cal_event_cats/1
  # PUT /cal_event_cats/1.xml
  def update
    @cal_event_cat = CalEventCat.find(params[:id])

    respond_to do |format|
      if @cal_event_cat.update_attributes(params[:cal_event_cat])
        format.html { redirect_to(@cal_event_cat, :notice => 'Cal event cat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cal_event_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cal_event_cats/1
  # DELETE /cal_event_cats/1.xml
  def destroy
    @cal_event_cat = CalEventCat.find(params[:id])
    @cal_event_cat.destroy

    respond_to do |format|
      format.html { redirect_to(cal_event_cats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cal_event_cats_helper.rb
module CalEventCatsHelper
end

app/views/cal_event_cats/_form.html.erb
<%= form_for(@cal_event_cat) do |f| %>
  <% if @cal_event_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cal_event_cat.errors.count, "error") %> prohibited this cal_event_cat from being saved:</h2>

      <ul>
      <% @cal_event_cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cal_event_cats/edit.html.erb
<h1>Editing cal_event_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cal_event_cat %> |
<%= link_to 'Back', cal_event_cats_path %>

app/views/cal_event_cats/index.html.erb
<h1>Listing cal_event_cats</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cal_event_cats.each do |cal_event_cat| %>
  <tr>
    <td><%= cal_event_cat.uid %></td>
    <td><%= cal_event_cat.name %></td>
    <td><%= cal_event_cat.description %></td>
    <td><%= link_to 'Show', cal_event_cat %></td>
    <td><%= link_to 'Edit', edit_cal_event_cat_path(cal_event_cat) %></td>
    <td><%= link_to 'Destroy', cal_event_cat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cal event cat', new_cal_event_cat_path %>

app/views/cal_event_cats/new.html.erb
<h1>New cal_event_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cal_event_cats_path %>

app/views/cal_event_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @cal_event_cat.uid %>
</p>

<p>
  <b>Name:</b>
  <%= @cal_event_cat.name %>
</p>

<p>
  <b>Description:</b>
  <%= @cal_event_cat.description %>
</p>


<%= link_to 'Edit', edit_cal_event_cat_path(@cal_event_cat) %> |
<%= link_to 'Back', cal_event_cats_path %>